global:
  scrape_interval: 5s  

scrape_configs:
  - job_name: "dotnet-app"
    static_configs:
      - targets: 
          - "host.docker.internal:5000" 
          - "host.docker.internal:5001" 

  - job_name: "system-metrics"
    static_configs:
      - targets: 
          - "localhost:9100" 
