global:
  scrape_interval: 5s  

scrape_configs:
  - job_name: "dotnet-app"
    scheme: "http"
    static_configs:
      - targets:           
          - "techchallenge.api:5000" 



      
