name: .NET Core Build and Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
    inputs:
      configuration:
        description: 'Build configuration'
        required: true
        default: 'Release'

jobs:

  build-and-test:

    strategy:
      matrix:
        configuration: [Debug, Release]

    runs-on: windows-latest

    env:
      Solution_Name: TechChallenge.sln                         
      Test_Project_Path: tests/TechChallenge.Tests/TechChallenge.Tests.csproj

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    # Install the .NET Core workload
    - name: Install .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    # Build the solution
    - name: Build solution
      run: dotnet build $env:Solution_Name --configuration ${{ matrix.configuration }}
      env:
        Configuration: ${{ matrix.configuration }}

    # Execute unit and integration tests
    - name: Execute unit and integration tests
      run: dotnet test $env:Test_Project_Path --configuration ${{ matrix.configuration }}
      env:
        Configuration: ${{ matrix.configuration }}
